version: '3'

services:
  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf

  php:
    build: docker/php
    volumes:
      - ./:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - JWT_PASSPHRASE=${JWT_PASSPHRASE}

  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
    - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

