# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Start docker
        run: docker-compose up -d

      - name: Install composer dependencies
        run: docker-compose exec -T php composer install --no-interaction
        uses: montudor/action-zip@v0.1.1
        with:
          args: zip -qq -r vendor.zip vendor

      - name: Upload vendor
        uses: actions/upload-artifact@v2
        with:
          name: vendor.zip

  test:
    runs-on: ubuntu-latest
    needs: [build]

    steps:

      - name: Download vendor
        uses: actions/download-artifact@v2
        with:
          name: vendor.zip

      - name: Unzip vendor
        uses: montudor/action-zip@v0.1.1
        with:
          args: unzip -qq vendor.zip -d vendor

      - name: Generate RSA keys for JWT
        run: docker-compose exec -T php bin/generate-keys

      - name: Create example OAuth2 Apps
        run: docker-compose exec php bin/console doctrine:migrations:migrate -n



